# Generated by Django 5.1.3 on 2024-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chasco', '0002_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Management_Pimages/')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='Member_Pimages/'),
        ),
    ]
